transition away from self-rolled querying to a document database, interactive python notebook, cli and bot do not work anymore, not a priority. a lot of reorganization. added tests.

diff --git a/git_hooks/pre-commit b/git_hooks/pre-commit
--- a/git_hooks/pre-commit
+++ b/git_hooks/pre-commit
@@ -1,8 +1,11 @@
 #!/bin/sh
 echo "Git pre-commit hook running now."
 #mypy update.py cli.py; 
-echo "Python's Black:"
-black .
-# echo "Quarto render (clean):" #this was way too slow.
-# . .venv/bin/activate
-#quarto render
+if pytest citutils/citutils/tests.py; then
+    echo "Python's Black:"
+    black .
+    # Add any other commands you want to run if tests pass here
+else
+    echo "Tests failed. Commit aborted."
+    exit 1
+fi
